baseURL: "https://TomGeorge1234.github.io" 
title: Tom George
pagination:
  pagerSize: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Home
          url: /
          weight: 1
        - name: More about me
          url: moreaboutme/
          weight: 2
        - name: Research
          url: papers/
          weight: 3
        - name: Teaching
          url: teaching/
          weight: 4
        - name: CV
          url: cv.pdf
          weight: 5
        - name: RatInABox
          url: https://github.com/RatInABox-Lab/RatInABox
          weight: 6
        - name: CaMinA
          url: https://trendinafrica.org/trend-camina/
          weight: 7

params:
    description: "because www.tom.com was taken"
    author: Tom
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Tom George
          subtitle: "Hi, I'm a **PhD student at UCL** studying **theoretical neuroscience and machine learning**. 
                    <br><br>
                    My research is in navigation, reinforcement and representation learning -- I use theoretical methods and data-driven techniques from machine learning to understand biological intelligence (NeuroAI) under the supervision of [**Kimberly Stachenfeld**](https://neurokim.com) (Google DeepMind), [**Claudia Clopath**](https://cclopath.bg-research.cc.ic.ac.uk) (Imperial) and [**Caswell Barry**](https://barry-lab.com) (UCL).
                    <br><br>
                    I build and maintain open-source tools for science including the [**RatInABox**](https://github.com/RatInABox-Lab/RatInABox) and [**SIMPL**](https://github.com/TomGeorge1234/simpl) packages. I recently completed an AI residency at [Google X](https://x.company) researching foundation models for geophysics. I also co-founded [**CaMinA,**](https://trendinafrica.org/trend-camina/) a summer school for computational neuroscience and machine learning in Africa.
                    <br><br>
                    **[Get in touch!](mailto:tom.george.20@ucl.ac.uk)** If any of the above interests you, or you are pursuing similar goals, I'd love to chat.
                    <br> 
                    *<small>[**defending soon.**](papers/phd_thesis/thesis.pdf) I'll be joining [Guillaume Lajoie](https://guillaumelajoie.com) and [Blake Richards](https://linclab.mila.quebec/team/blake) at Mila, in Montreal, September 2025.</small>
                    "
          imageUrl: "tomgeorge.png"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Tom
          buttons:
            - name: More about me
              url: moreaboutme/
            - name: Research
              url: papers/
            - name: Teaching
              url: teaching/
            - name: CV
              url: cv.pdf
            - name: RatInABox
              url: https://github.com/RatInABox-Lab/RatInABox
            - name: CaMinA
              url: https://trendinafrica.org/trend-camina/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:tom.george.20@ucl.ac.uk
        # - name: LinkedIn
          # url: https://www.linkedin.com/in/tom-george-8170ba173/
        - name : Google Scholar
          url: https://scholar.google.com/citations?user=AG49j3MAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/TomGeorge1234
        - name: Twitter
          url: https://twitter.com/tomnotgeorge
        # - name: Zoom
          # url: https://ucl.zoom.us/my/zoom.tom.george 

    
    social:
        github: TomGeorge1234
        twitter: tomnotgeorge
        linkedin: tom-george-8170ba173


    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Tom George"
      icon: picture.png
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
