baseURL: "https://TomGeorge1234.github.io" 
title: Tom George
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: papers/
          weight: 2
        - name: Work in Progress
          url: wp/
          weight: 3
        - name: Home
          url: /
          weight: 1
         # url: data/
          #weight: 3 
        #- name: Readings
         # url: readings/
          #weight: 4

params:
    description: "Tom George's personal website"
    author: Tom
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Tom George
          subtitle: "Hello! I'm at PhD student at UCL studying **theoretical neuroscience and machine learning**. My research covers topics in **spatial navigation, reinforcement learning and representation learning** -- using theory and data-driven principles from machine learning I try to shed light on the fundamental principles of biological intelligence. I do this under the supervision of [**Kim Stachenfeld**](https://neurokim.com) (Google DeepMind), [**Claudia Clopath**](https://cclopath.bg-research.cc.ic.ac.uk) (Imperial) and [**Caswell Barry**](https://barry-lab.com) (UCL).
          <br><br>
          To achieve these goals I also build and maintain open-source tools for computational neuroscience including the [**RatInABox**](https://github.com/RatInABox-Lab/RatInABox) package. 
          <br><br>
          I also co-organise a [**CaMinA**](https://trendinafrica.org/trend-camina/), a residential summer school for computational neuroscience and machine learning, held each year in Africa dedicated to the promotion of open-source teaching materials and the development of a community of computational neuroscientists in Africa. 
          <br><br>
          If any of the above is of interest, get in touch! I'd really would love to chat."
          imageUrl: "picture.png"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Tom
          buttons:
            - name: Research
              url: papers/
            - name: Open source
              url: open_source/
            - name: Talks
              url: talks/
            - name: CaMinA
              url: camina/
            - name: Blog
              url: blog/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:tom.george.20@ucl.ac.uk
        - name: LinkedIn
          url: https://www.linkedin.com/in/tom-george-8170ba173/
        - name : Google Scholar
          url: https://scholar.google.com/citations?user=AG49j3MAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/TomGeorge1234
        - name: Twitter
          url: https://twitter.com/tomnotgeorge

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Tom George"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2