baseURL: "https://TomGeorge1234.github.io" 
title: Tom George
pagination:
  pagerSize: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: papers/
          weight: 2
        - name: Work in Progress
          url: wp/
          weight: 3
        - name: Home
          url: /
          weight: 1
         # url: data/
          #weight: 3 
        #- name: Readings
         # url: readings/
          #weight: 4

params:
    description: "Tom George's personal website"
    author: Tom
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Tom George
          subtitle: "Hi, I'm at PhD student at UCL$^*$ studying theoretical neuroscience and machine learning. 
                    <br><br>
                    My research is in spatial navigation, reinforcement learning and representation learning -- I use theory and data-driven principles from machine learning to understand  biological intelligence (NeuroAI) under the supervision of [**Kimberly Stachenfeld**](https://neurokim.com) (Google DeepMind), [**Claudia Clopath**](https://cclopath.bg-research.cc.ic.ac.uk) (Imperial) and [**Caswell Barry**](https://barry-lab.com) (UCL).
                    <br><br>
                    I build and maintain open-source tools for science including the [**RatInABox**](https://github.com/RatInABox-Lab/RatInABox) package. I also co-founded [**CaMinA,**](https://trendinafrica.org/trend-camina/) a summer school for computational neuroscience and machine learning in Africa.
                    <br><br>
                    * 
                    submitting soon and seeking postdocs. I'll be doing an AI residency at [Google X](https://x.company) until Autumn 2025.
                    "
                    
          imageUrl: "picture.png"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Tom
          buttons:
            - name: More about me
              url: moreaboutme/
            - name: Research
              url: papers/
            - name: Open source
              url: open_source/
            - name: Talks
              url: talks/
            - name: CaMinA
              url: camina/
            # - name: Blog
            #   url: blog/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:tom.george.20@ucl.ac.uk
        - name: LinkedIn
          url: https://www.linkedin.com/in/tom-george-8170ba173/
        - name : Google Scholar
          url: https://scholar.google.com/citations?user=AG49j3MAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/TomGeorge1234
        - name: Twitter
          url: https://twitter.com/tomnotgeorge
    
    social:
        github: TomGeorge1234
        twitter: tomnotgeorge
        linkedin: tom-george-8170ba173


    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Tom George"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2