baseURL: "https://TomGeorge1234.github.io" 
title: Tom George
pagination:
  pagerSize: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Home
          url: /
          weight: 1
        - name: More about me
          url: moreaboutme/
          weight: 2
        - name: Research
          url: papers/
          weight: 3
        - name: Teaching
          url: teaching/
          weight: 4
        - name: CV
          url: cv.pdf
          weight: 5
        - name: RatInABox
          url: https://github.com/RatInABox-Lab/RatInABox
          weight: 6
        - name: CaMinA
          url: camina/
          weight: 7

params:
    description: "because www.tom.com was taken"
    author: Tom
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Tom George
          subtitle: "Hi, I'm a post-doctoral fellow and [Canadian Neuroanalytics Scholar](https://www.albertaneuro.ca/funding-programs/canadian-neuroanalytics-scholars-program/) at **Mila** (the Quebec AI Institute) with [**Blake Richards**](https://linclab.mila.quebec/team/blake) and [**Guillaume Lajoie**.](https://guillaumelajoie.com)
                    <br><br>
                    I [research](papers) **theoretical neuroscience and machine learning** with a focus on spatial cognition, latent variable models and foundation models.  My [PhD](papers/phd_thesis/thesis.pdf) was at UCL under the supervision of [**Claudia Clopath**,](https://cclopath.bg-research.cc.ic.ac.uk) [**Caswell Barry**](https://barry-lab.com) and [**Kimberly Stachenfeld**.](https://neurokim.com)
                    <br><br>
                    I build open-source tools for science including the [**RatInABox**](https://github.com/RatInABox-Lab/RatInABox) and [**SIMPL**](https://github.com/TomGeorge1234/simpl) packages. I recently completed an AI residency at [Google X](https://x.company) on foundation modelling. I also co-founded the [**CaMinA**,](camina/) a summer school for computational neuroscience and machine learning in Africa.
                    <br><br>
                    **[Get in touch!](mailto:tom.george.20@ucl.ac.uk)** If any of the above interests you, or you are pursuing similar goals, I'd love to chat.
                    <br> 
                    "
          imageUrl: "tomgeorge.png"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Tom
          buttons:
            - name: More about me
              url: moreaboutme/
            - name: Research
              url: papers/
            - name: Teaching
              url: teaching/
            - name: CV
              url: cv.pdf
            - name: RatInABox
              url: https://github.com/RatInABox-Lab/RatInABox
            - name: CaMinA
              url: camina/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:tom.george@mila.quebec
        # - name: LinkedIn
          # url: https://www.linkedin.com/in/tom-george-8170ba173/
        - name : Google Scholar
          url: https://scholar.google.com/citations?user=AG49j3MAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/TomGeorge1234
        - name: Twitter
          url: https://twitter.com/tomnotgeorge
        # - name: Zoom
          # url: https://ucl.zoom.us/my/zoom.tom.george 

    
    social:
        github: TomGeorge1234
        twitter: tomnotgeorge
        linkedin: tom-george-8170ba173


    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Tom George"
      icon: picture.png
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
